### ISSUE TITLE
'Network' object has no attribute '_population'

### ISSUE THREAD

**Issue by MalloryDazza** [Silmathoron/NNGT#29]
Voila le message d'erreur : 

Traceback (most recent call last):
  File "Simulation_DenseNet.py", line 88, in <module>
    net = nngt.Network(from_graph = graph, population = pop)
  File "/home/mallory/Documents/Software/NNGT/nngt/core/graph_classes.py", line 1440, in __init__
    **kwargs)
  File "/home/mallory/Documents/Software/NNGT/nngt/core/graph_classes.py", line 336, in __init__
    directed=directed, weighted=weighted)
  File "/home/mallory/Documents/Software/NNGT/nngt/core/ig_graph.py", line 248, in __init__
    check_edges=False)
  File "/home/mallory/Documents/Software/NNGT/nngt/core/ig_graph.py", line 425, in new_edges
    self.attr_new_edges(edge_list, attributes=new_attr)
  File "/home/mallory/Documents/Software/NNGT/nngt/core/base_graph.py", line 206, in attr_new_edges
    for syn_param in self.population.syn_spec.values():
  File "/home/mallory/Documents/Software/NNGT/nngt/core/graph_classes.py", line 1456, in population
    return self._population
AttributeError: 'Network' object has no attribute '_population'

**Comment by Silmathoron** [comment]
Fixed (quite a while aga actually... ^^")
