### ISSUE TITLE
bug in AnimationNetwork.save_movie()

### ISSUE THREAD

**Issue by MalloryDazza** [Silmathoron/NNGT#30]
Traceback (most recent call last):
  File "RQA.py", line 65, in <module>
    animation = True, anim_name = 'anim_test_file1.mp4')
  File "/home/mallory/Documents/These/september2018/Recurrence Quantification Analysis/Simulation.py", line 235, in Simulation
    anim.save_movie(anim_name, interval = 20., fps = 15)
  File "/home/mallory/Documents/Software/NNGT/nngt/plot/animations.py", line 336, in save_movie
    self.fig.dpi)
  File "/home/mallory/Documents/Software/NNGT/nngt/plot/animations.py", line 818, in _save_movie
    animation.save(filename, writer=writer, dpi=dpi)
  File "/home/mallory/.local/lib/python2.7/site-packages/matplotlib/animation.py", line 1195, in save
    anim._init_draw()
  File "/home/mallory/Documents/Software/NNGT/nngt/plot/animations.py", line 742, in _init_draw
    tight=False, **self.kwargs)
  File "/home/mallory/Documents/Software/NNGT/nngt/plot/plt_networks.py", line 188, in draw_network
    node_color, nticks, ntickslabels, nlabel = _node_color(network, ncolor)
  File "/home/mallory/Documents/Software/NNGT/nngt/plot/plt_networks.py", line 507, in _node_color
    raise RuntimeError("Invalid `ncolor`: {}.".format(ncolor))
RuntimeError: Invalid `ncolor`: k.

**Comment by Silmathoron** [comment]
Fixed some time ago
